using System;
using System.Collections.Generic;
using System.Linq;
using Content.Shared.FixedPoint;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Client.UserInterface;
using Robust.Shared.IoC;
using Robust.Shared.GameObjects;
using RobustoClient.Systems.AutoChem;
using System.Numerics;

namespace RobustoClient.UI;

[GenerateTypedNameReferences]
public sealed partial class AutoChemWindow : DefaultWindow
{
    [Dependency] private readonly IEntityManager _entMan = default!;
    private readonly RobustaAutoChemSystem _autoChem;

    private string _selectedChem = "";

    public AutoChemWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        _autoChem = _entMan.System<RobustaAutoChemSystem>();

        if (!RobustaChemDatabase.IsInitialized)
            RobustaChemDatabase.Initialize();

        SearchBar.OnTextChanged += args => UpdateChemList(args.Text);
        StartStopButton.OnPressed += OnStartStopPressed;

        UpdateChemList("");
    }

    private void UpdateChemList(string query)
    {
        ChemListContainer.Children.Clear();

        IEnumerable<string> chems = RobustaChemDatabase.RecipesByProduct.Keys;
        if (!string.IsNullOrWhiteSpace(query))
        {
            chems = chems.Where(k => k.Contains(query, StringComparison.OrdinalIgnoreCase));
        }

        foreach (var chemId in chems.OrderBy(k => k))
        {
            var recipe = RobustaChemDatabase.GetRecipe(chemId);
            if (recipe == null) continue;

            var chemBox = new BoxContainer
            {
                Orientation = BoxContainer.LayoutOrientation.Vertical,
                HorizontalExpand = true,
                Margin = new Robust.Shared.Maths.Thickness(4)
            };

            var topRow = new BoxContainer
            {
                Orientation = BoxContainer.LayoutOrientation.Horizontal,
                HorizontalExpand = true
            };

            var nameLabel = new Label
            {
                Text = chemId,
                HorizontalExpand = true
            };

            var recipeButton = new Button { Text = "Recipe" };
            var selectButton = new Button { Text = "Select", StyleClasses = { "ButtonColorGreen" } };

            topRow.Children.Add(nameLabel);
            topRow.Children.Add(recipeButton);
            topRow.Children.Add(new Control { MinSize = new Vector2(4, 0) });
            topRow.Children.Add(selectButton);

            var recipeDetails = new BoxContainer
            {
                Orientation = BoxContainer.LayoutOrientation.Vertical,
                Visible = false,
                Margin = new Robust.Shared.Maths.Thickness(10, 2, 0, 0)
            };

            foreach (var (reactant, info) in recipe.Reactants)
            {
                recipeDetails.Children.Add(new Label { Text = $"- {reactant}: {info.Amount}u", FontColorOverride = Robust.Shared.Maths.Color.LightGray });
            }
            if (recipe.MinimumTemperature > 295f)
            {
                recipeDetails.Children.Add(new Label { Text = $"- Requires Heating ({recipe.MinimumTemperature}K)", FontColorOverride = Robust.Shared.Maths.Color.Orange });
            }

            recipeButton.OnPressed += _ => recipeDetails.Visible = !recipeDetails.Visible;
            selectButton.OnPressed += _ => SelectChem(chemId);

            chemBox.Children.Add(topRow);
            chemBox.Children.Add(recipeDetails);

            ChemListContainer.Children.Add(chemBox);
        }
    }

    private void SelectChem(string chemId)
    {
        _selectedChem = chemId;
        StatusLabel.Text = $"Selected: {chemId}";
        StatusLabel.FontColorOverride = Robust.Shared.Maths.Color.LightGreen;
    }

    private void OnStartStopPressed(Robust.Client.UserInterface.Controls.BaseButton.ButtonEventArgs args)
    {
        if (_autoChem.CurrentState.GetType() != typeof(IdleState))
        {
            _autoChem.StopJob();
            StartStopButton.Text = "Start";
            StartStopButton.StyleClasses.Remove("ButtonColorRed");
            StartStopButton.StyleClasses.Add("ButtonColorGreen");
            StatusLabel.Text = "Job stopped.";
            StatusLabel.FontColorOverride = Robust.Shared.Maths.Color.Yellow;
            return;
        }

        if (string.IsNullOrWhiteSpace(_selectedChem))
        {
            StatusLabel.Text = "Please select a chemical first!";
            StatusLabel.FontColorOverride = Robust.Shared.Maths.Color.Red;
            return;
        }

        if (!int.TryParse(AmountInput.Text, out var amountInt) || amountInt <= 0)
        {
            StatusLabel.Text = "Invalid amount!";
            StatusLabel.FontColorOverride = Robust.Shared.Maths.Color.Red;
            return;
        }

        _autoChem.StartJob(_selectedChem, FixedPoint2.New(amountInt));

        StartStopButton.Text = "Stop";
        StartStopButton.StyleClasses.Remove("ButtonColorGreen");
        StartStopButton.StyleClasses.Add("ButtonColorRed");
        StatusLabel.Text = $"Brewing {_selectedChem} ({amountInt}u)...";
        StatusLabel.FontColorOverride = Robust.Shared.Maths.Color.Cyan;
    }

    protected override void FrameUpdate(Robust.Shared.Timing.FrameEventArgs args)
    {
        base.FrameUpdate(args);

        if (_autoChem.CurrentState.GetType() != typeof(IdleState))
        {
            StatusLabel.Text = _autoChem.GetStatusInfo();
        }
        else if (StartStopButton.Text == "Stop")
        {
            StartStopButton.Text = "Start";
            StartStopButton.StyleClasses.Remove("ButtonColorRed");
            StartStopButton.StyleClasses.Add("ButtonColorGreen");
            StatusLabel.Text = $"Selected: {_selectedChem}";
            StatusLabel.FontColorOverride = Robust.Shared.Maths.Color.LightGreen;
        }
    }
}
