using RobustoClient.Systems;
using RobustoClient.UI.Controls;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.GameObjects;
using Robust.Shared.IoC;

namespace RobustoClient.UI;

[GenerateTypedNameReferences]
public sealed partial class CheatMenuWindow : RobustaWindow
{
    [Dependency] private readonly IEntityManager _entMan = default!;
    
    private readonly RobustaDiscordSystem? _robustaDiscord;

    public CheatMenuWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
        _robustaDiscord ??= _entMan.System<RobustaDiscordSystem>();
        
        TitleLabel.Text = "ROBUSTA CLIENT | PREMIUM";
        
        // Sync with config
        Ranged.Pressed = RobustaConfig.RangedAimbotEnabled;
        Melee.Pressed = RobustaConfig.MeleeAimbotEnabled;
        MeleeTrigger.Pressed = RobustaConfig.MeleeTriggerbotEnabled;
        AutoSpin.Pressed = RobustaConfig.SpinBotEnabled;
        AntiSlip.Pressed = RobustaConfig.AntiSlipEnabled;
        SyndicateDetector.Pressed = RobustaConfig.SyndicateDetector;
        DOD.Pressed = RobustaConfig.FOVDisable;
        OverlaysDisable.Pressed = RobustaConfig.OverlaysDisable;
        NoRecoil.Pressed = RobustaConfig.NoRecoilEnabled;
        FullbrightBtn.Pressed = RobustaConfig.FullbrightEnabled;
        EspBtn.Pressed = RobustaConfig.EspEnabled;
        ItemSearchInput.Text = RobustaConfig.ItemSearchQuery;
        ItemSearchBtn.Pressed = RobustaConfig.ItemSearchEnabled;
        PredictionToggle.Pressed = RobustaConfig.UsePrediction;

        // Button Handlers
        Melee.OnToggled += args => RobustaConfig.MeleeAimbotEnabled = args.Pressed;
        MeleeTrigger.OnToggled += args => RobustaConfig.MeleeTriggerbotEnabled = args.Pressed;
        Ranged.OnToggled += args => RobustaConfig.RangedAimbotEnabled = args.Pressed;
        AutoSpin.OnToggled += args => RobustaConfig.SpinBotEnabled = args.Pressed;
        AntiSlip.OnToggled += args => RobustaConfig.AntiSlipEnabled = args.Pressed;
        SyndicateDetector.OnToggled += args => RobustaConfig.SyndicateDetector = args.Pressed;
        DOD.OnToggled += args => RobustaConfig.FOVDisable = args.Pressed;
        OverlaysDisable.OnToggled += args => RobustaConfig.OverlaysDisable = args.Pressed;
        NoRecoil.OnToggled += args => RobustaConfig.NoRecoilEnabled = args.Pressed;
        FullbrightBtn.OnToggled += args => RobustaConfig.FullbrightEnabled = args.Pressed;
        EspBtn.OnToggled += args => RobustaConfig.EspEnabled = args.Pressed;
        ItemSearchInput.OnTextChanged += args => RobustaConfig.ItemSearchQuery = args.Text;
        ItemSearchBtn.OnToggled += args => RobustaConfig.ItemSearchEnabled = args.Pressed;
        PredictionToggle.OnToggled += args => RobustaConfig.UsePrediction = args.Pressed;
        
        Discord.OnPressed += _ => _robustaDiscord?.OpenDiscord();
        OpenMapBtn.OnPressed += _ => RobustaMapOpener.Show();
        OpenTacticalRadarBtn.OnPressed += _ => RobustaRadarOpener.Show();

        // Ping Handlers
        PingLocal.OnPressed += _ => SetPingMode(RobustaConfig.PingMode.Local);
        PingStable.OnPressed += _ => SetPingMode(RobustaConfig.PingMode.Stable);
        PingLaggy.OnPressed += _ => SetPingMode(RobustaConfig.PingMode.Laggy);
        PingAuto.OnPressed += _ => SetPingMode(RobustaConfig.PingMode.Auto);
        UpdatePingButtons();

        // Tab Navigation
        TabCombat.OnPressed += _ => ShowSection(CombatSection);
        TabVisuals.OnPressed += _ => ShowSection(VisualsSection);
        TabUtility.OnPressed += _ => ShowSection(UtilitySection);

        // Default view
        ShowSection(CombatSection);
    }

    private void SetPingMode(RobustaConfig.PingMode mode)
    {
        RobustaConfig.CurrentPingMode = mode;
        Robust.Shared.Log.Logger.GetSawmill("RobustaAim").Info($"> Ping Mode set to: {mode}");
        UpdatePingButtons();
    }

    private void UpdatePingButtons()
    {
        // Удаляем все возможные цветовые классы перед добавлением нужного
        string[] colors = { "ButtonColorGreen", "ButtonColorRed" };
        foreach (var color in colors)
        {
            PingLocal.StyleClasses.Remove(color);
            PingStable.StyleClasses.Remove(color);
            PingLaggy.StyleClasses.Remove(color);
            PingAuto.StyleClasses.Remove(color);
        }

        switch (RobustaConfig.CurrentPingMode)
        {
            case RobustaConfig.PingMode.Local: PingLocal.StyleClasses.Add("ButtonColorGreen"); break;
            case RobustaConfig.PingMode.Stable: PingStable.StyleClasses.Add("ButtonColorGreen"); break;
            case RobustaConfig.PingMode.Laggy: PingLaggy.StyleClasses.Add("ButtonColorGreen"); break;
            case RobustaConfig.PingMode.Auto: PingAuto.StyleClasses.Add("ButtonColorGreen"); break;
        }
    }

    private void ShowSection(Control section)
    {
        CombatSection.Visible = (section == CombatSection);
        VisualsSection.Visible = (section == VisualsSection);
        UtilitySection.Visible = (section == UtilitySection);
        
        // Optional: Update button styles to show active tab
        TabCombat.StyleClasses.Remove("ButtonColorGreen");
        TabVisuals.StyleClasses.Remove("ButtonColorGreen");
        TabUtility.StyleClasses.Remove("ButtonColorGreen");

        if (section == CombatSection) TabCombat.StyleClasses.Add("ButtonColorGreen");
        if (section == VisualsSection) TabVisuals.StyleClasses.Add("ButtonColorGreen");
        if (section == UtilitySection) TabUtility.StyleClasses.Add("ButtonColorGreen");
    }
}