using ArabicaCliento.Systems;
using ArabicaCliento.UI.Controls;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;

namespace ArabicaCliento.UI;

[GenerateTypedNameReferences]
public sealed partial class CheatMenuWindow : ArabicaWindow
{
    [Dependency] private readonly IEntityManager _entMan = default!;
    
    private readonly ArabicaDiscordSystem? _arabicaDiscord;

    public CheatMenuWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
        _arabicaDiscord ??= _entMan.System<ArabicaDiscordSystem>();
        TitleLabel.Text = "ArabicaCliento: Click GUI";
        Ranged.Pressed = ArabicaConfig.RangedAimbotEnabled;
        Melee.Pressed = ArabicaConfig.MeleeAimbotEnabled;
        MeleeTrigger.Pressed = ArabicaConfig.MeleeTriggerbotEnabled;
        AutoSpin.Pressed = ArabicaConfig.SpinBotEnabled;
        AntiSlip.Pressed = ArabicaConfig.AntiSlipEnabled;
        SyndicateDetector.Pressed = ArabicaConfig.SyndicateDetector;
        DOD.Pressed = ArabicaConfig.FOVDisable;
        OverlaysDisable.Pressed = ArabicaConfig.OverlaysDisable;
        NoRecoil.Pressed = ArabicaConfig.NoRecoilEnabled;
        FullbrightBtn.Pressed = ArabicaConfig.FullbrightEnabled;
        EspBtn.Pressed = ArabicaConfig.EspEnabled;
        ItemSearchInput.Text = ArabicaConfig.ItemSearchQuery;
        ItemSearchBtn.Pressed = ArabicaConfig.ItemSearchEnabled;
        PredictionToggle.Pressed = ArabicaConfig.UsePrediction;
        //LogPlayers.Pressed = ArabicaConfig.LogPlayers;

        Melee.OnToggled += args => ArabicaConfig.MeleeAimbotEnabled = args.Pressed;
        MeleeTrigger.OnToggled += args => ArabicaConfig.MeleeTriggerbotEnabled = args.Pressed;
        Ranged.OnToggled += args => ArabicaConfig.RangedAimbotEnabled = args.Pressed;
        AutoSpin.OnToggled += args => ArabicaConfig.SpinBotEnabled = args.Pressed;
        AntiSlip.OnToggled += args => ArabicaConfig.AntiSlipEnabled = args.Pressed;
        SyndicateDetector.OnToggled += args => ArabicaConfig.SyndicateDetector = args.Pressed;
        DOD.OnToggled += args => ArabicaConfig.FOVDisable = args.Pressed;
        OverlaysDisable.OnToggled += args => ArabicaConfig.OverlaysDisable = args.Pressed;
        NoRecoil.OnToggled += args => ArabicaConfig.NoRecoilEnabled = args.Pressed;
        FullbrightBtn.OnToggled += args => ArabicaConfig.FullbrightEnabled = args.Pressed;
        EspBtn.OnToggled += args => ArabicaConfig.EspEnabled = args.Pressed;
        ItemSearchInput.OnTextChanged += args => ArabicaConfig.ItemSearchQuery = args.Text;
        ItemSearchBtn.OnToggled += args => ArabicaConfig.ItemSearchEnabled = args.Pressed;
        PredictionToggle.OnToggled += args => ArabicaConfig.UsePrediction = args.Pressed;

        
        Discord.OnPressed += _ => _arabicaDiscord?.OpenDiscord();
        OpenMapBtn.OnPressed += _ => ArabicaMapOpener.Show();

        OpenTacticalRadarBtn.OnPressed += _ => ArabicaRadarOpener.Show();
        //LogPlayers.OnToggled += args => ArabicaConfig.LogPlayers = args.Pressed;
    }
}