using ArabicaCliento.Systems;
using ArabicaCliento.UI.Controls;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.GameObjects;
using Robust.Shared.IoC;

namespace ArabicaCliento.UI;

[GenerateTypedNameReferences]
public sealed partial class CheatMenuWindow : ArabicaWindow
{
    [Dependency] private readonly IEntityManager _entMan = default!;
    
    private readonly ArabicaDiscordSystem? _arabicaDiscord;

    public CheatMenuWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
        _arabicaDiscord ??= _entMan.System<ArabicaDiscordSystem>();
        
        TitleLabel.Text = "ARABICA CLIENT | PREMIUM";
        
        // Sync with config
        Ranged.Pressed = ArabicaConfig.RangedAimbotEnabled;
        Melee.Pressed = ArabicaConfig.MeleeAimbotEnabled;
        MeleeTrigger.Pressed = ArabicaConfig.MeleeTriggerbotEnabled;
        AutoSpin.Pressed = ArabicaConfig.SpinBotEnabled;
        AntiSlip.Pressed = ArabicaConfig.AntiSlipEnabled;
        SyndicateDetector.Pressed = ArabicaConfig.SyndicateDetector;
        DOD.Pressed = ArabicaConfig.FOVDisable;
        OverlaysDisable.Pressed = ArabicaConfig.OverlaysDisable;
        NoRecoil.Pressed = ArabicaConfig.NoRecoilEnabled;
        FullbrightBtn.Pressed = ArabicaConfig.FullbrightEnabled;
        EspBtn.Pressed = ArabicaConfig.EspEnabled;
        ItemSearchInput.Text = ArabicaConfig.ItemSearchQuery;
        ItemSearchBtn.Pressed = ArabicaConfig.ItemSearchEnabled;
        PredictionToggle.Pressed = ArabicaConfig.UsePrediction;

        // Button Handlers
        Melee.OnToggled += args => ArabicaConfig.MeleeAimbotEnabled = args.Pressed;
        MeleeTrigger.OnToggled += args => ArabicaConfig.MeleeTriggerbotEnabled = args.Pressed;
        Ranged.OnToggled += args => ArabicaConfig.RangedAimbotEnabled = args.Pressed;
        AutoSpin.OnToggled += args => ArabicaConfig.SpinBotEnabled = args.Pressed;
        AntiSlip.OnToggled += args => ArabicaConfig.AntiSlipEnabled = args.Pressed;
        SyndicateDetector.OnToggled += args => ArabicaConfig.SyndicateDetector = args.Pressed;
        DOD.OnToggled += args => ArabicaConfig.FOVDisable = args.Pressed;
        OverlaysDisable.OnToggled += args => ArabicaConfig.OverlaysDisable = args.Pressed;
        NoRecoil.OnToggled += args => ArabicaConfig.NoRecoilEnabled = args.Pressed;
        FullbrightBtn.OnToggled += args => ArabicaConfig.FullbrightEnabled = args.Pressed;
        EspBtn.OnToggled += args => ArabicaConfig.EspEnabled = args.Pressed;
        ItemSearchInput.OnTextChanged += args => ArabicaConfig.ItemSearchQuery = args.Text;
        ItemSearchBtn.OnToggled += args => ArabicaConfig.ItemSearchEnabled = args.Pressed;
        PredictionToggle.OnToggled += args => ArabicaConfig.UsePrediction = args.Pressed;
        
        Discord.OnPressed += _ => _arabicaDiscord?.OpenDiscord();
        OpenMapBtn.OnPressed += _ => ArabicaMapOpener.Show();
        OpenTacticalRadarBtn.OnPressed += _ => ArabicaRadarOpener.Show();

        // Ping Handlers
        PingLocal.OnPressed += _ => SetPingMode(ArabicaConfig.PingMode.Local);
        PingStable.OnPressed += _ => SetPingMode(ArabicaConfig.PingMode.Stable);
        PingLaggy.OnPressed += _ => SetPingMode(ArabicaConfig.PingMode.Laggy);
        PingAuto.OnPressed += _ => SetPingMode(ArabicaConfig.PingMode.Auto);
        UpdatePingButtons();

        // Tab Navigation
        TabCombat.OnPressed += _ => ShowSection(CombatSection);
        TabVisuals.OnPressed += _ => ShowSection(VisualsSection);
        TabUtility.OnPressed += _ => ShowSection(UtilitySection);

        // Default view
        ShowSection(CombatSection);
    }

    private void SetPingMode(ArabicaConfig.PingMode mode)
    {
        ArabicaConfig.CurrentPingMode = mode;
        Robust.Shared.Log.Logger.GetSawmill("ArabicaAim").Info($"> Ping Mode set to: {mode}");
        UpdatePingButtons();
    }

    private void UpdatePingButtons()
    {
        // Удаляем все возможные цветовые классы перед добавлением нужного
        string[] colors = { "ButtonColorGreen", "ButtonColorRed" };
        foreach (var color in colors)
        {
            PingLocal.StyleClasses.Remove(color);
            PingStable.StyleClasses.Remove(color);
            PingLaggy.StyleClasses.Remove(color);
            PingAuto.StyleClasses.Remove(color);
        }

        switch (ArabicaConfig.CurrentPingMode)
        {
            case ArabicaConfig.PingMode.Local: PingLocal.StyleClasses.Add("ButtonColorGreen"); break;
            case ArabicaConfig.PingMode.Stable: PingStable.StyleClasses.Add("ButtonColorGreen"); break;
            case ArabicaConfig.PingMode.Laggy: PingLaggy.StyleClasses.Add("ButtonColorGreen"); break;
            case ArabicaConfig.PingMode.Auto: PingAuto.StyleClasses.Add("ButtonColorGreen"); break;
        }
    }

    private void ShowSection(Control section)
    {
        CombatSection.Visible = (section == CombatSection);
        VisualsSection.Visible = (section == VisualsSection);
        UtilitySection.Visible = (section == UtilitySection);
        
        // Optional: Update button styles to show active tab
        TabCombat.StyleClasses.Remove("ButtonColorGreen");
        TabVisuals.StyleClasses.Remove("ButtonColorGreen");
        TabUtility.StyleClasses.Remove("ButtonColorGreen");

        if (section == CombatSection) TabCombat.StyleClasses.Add("ButtonColorGreen");
        if (section == VisualsSection) TabVisuals.StyleClasses.Add("ButtonColorGreen");
        if (section == UtilitySection) TabUtility.StyleClasses.Add("ButtonColorGreen");
    }
}