name: Brewing RobustoClient Release

on:
  push:
    tags:
      - 'v*' # We start brewing when a new version tag appears (for example, v1.0.0)
  workflow_dispatch: # Button for manual start of the coffee machine

jobs:
  brew:
    name: Make Robusta Coffee
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: Harvest coffee beans (Download sources)
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Setup Roasting Machine (.NET 10.0)
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '10.0.x'

    - name: Roast the beans (Restore dependencies)
      run: dotnet restore RobustoClient.sln
        
    - name: Brew the strongest espresso (Build Release)
      run: dotnet build RobustoClient/RobustoClient.csproj -c Release
        
    - name: Serve the coffee (Upload Release Artifact)
      uses: softprops/action-gh-release@v2
      with:
        files: ./RobustoClient/bin/Release/net10.0/RobustoClient.dll
        generate_release_notes: true
        tag_name: ${{ github.ref_type == 'tag' && github.ref_name || 'rolling-release' }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}